name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build (${{ matrix.os }}, ${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [windows, linux, macos]
        arch: [x86_64, aarch64]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Build Binary
        run: |
          zig build -Dtarget=${{ matrix.arch }}-${{ matrix.os }} -Doptimize=ReleaseFast
          
          # Prepare binary name
          BINARY_NAME="matrix-string-generator-${{ matrix.os }}-${{ matrix.arch }}"
          if [ "${{ matrix.os }}" = "windows" ]; then
            BINARY_NAME="${BINARY_NAME}.exe"
          fi
          
          # Copy binary to properly named file
          cp zig-out/bin/matrix-string-generator* "${BINARY_NAME}"
          
          # Create checksum
          sha256sum "${BINARY_NAME}" > "${BINARY_NAME}.sha256"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            matrix-string-generator-${{ matrix.os }}-${{ matrix.arch }}*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.sha }}
          files: ./artifacts/*
          token: ${{ secrets.GITHUB_TOKEN }} 