name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build All Targets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Build All Targets
        run: |
          # Array of targets to build
          targets=(
            "x86_64-windows"
            "aarch64-windows"
            "x86_64-linux"
            "aarch64-linux"
            "x86_64-macos"
            "aarch64-macos"
          )
          
          for target in "${targets[@]}"; do
            echo "Building for $target..."
            zig build -Dtarget=$target -Doptimize=ReleaseFast

            ls zig-out/bin
            
            # Parse OS and arch from target
            os=$(echo $target | cut -d'-' -f2)
            arch=$(echo $target | cut -d'-' -f1)
            
            # Prepare binary name
            BINARY_NAME="matrix-string-generator-${os}-${arch}"
            if [ "$os" = "windows" ]; then
              BINARY_NAME="${BINARY_NAME}.exe"
              find zig-out/bin -name "matrix-string-generator*.exe" -exec cp {} "${BINARY_NAME}" \;
            else
              find zig-out/bin -name "matrix-string-generator" -exec cp {} "${BINARY_NAME}" \;
            fi
            
            # Create checksum
            sha256sum "${BINARY_NAME}" > "${BINARY_NAME}.sha256"
            
            # Clean zig-out to prepare for next build
            rm -rf zig-out/
          done

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: matrix-string-generator-*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.sha }}
          files: ./artifacts/*
          token: ${{ secrets.GITHUB_TOKEN }} 